#!/usr/bin/env bash

echo "Setting up workspaces..."

# Remove cli-website/public/workspaces directory
rm -rf cli-website/public/workspaces

# Validation
# Validate that meta.json exists for each workspace
if ! find workspaces -mindepth 2 -maxdepth 2 -name "meta.json" | grep -q .; then
    echo "Error: No meta.json files found in workspaces"
    exit 1
fi

# For each workspace in workspaces directory:
#   - make a directory `cli-website/public/workspaces/$w`
#   - copy the workspace's meta.json to `cli-website/public/workspaces/$w/meta.json`
for w in $(ls -d workspaces/*/); do
    w=${w%/}
    w=${w#workspaces/}
    mkdir -p "cli-website/public/workspaces/$w"
    echo "Created directory: cli-website/public/workspaces/$w"

    cp "workspaces/$w/meta.json" "cli-website/public/workspaces/$w/meta.json"
    echo "Copied meta.json to cli-website/public/workspaces/$w/meta.json"

    tar -czf "cli-website/public/workspaces/$w/download.tar.gz" -C "workspaces/$w" .
    echo "Created gzipped archive: cli-website/public/workspaces/$w/download.tar.gz"
done

# Next create a typescript file at ahh-binary/src/workspace/choices.ts
# Which exports an array called WORKSPACE_CHOICES with the name of each workspace
# Also specify in a comment at the bottom of the file that this file is auto-generated

mkdir -p ahh-binary/src/workspace
rm -f ahh-binary/src/workspace/choices.ts
touch ahh-binary/src/workspace/choices.ts
echo "export const WORKSPACE_CHOICES = [" > ahh-binary/src/workspace/choices.ts
for w in $(ls -d workspaces/*/); do
    w=${w%/}
    w=${w#workspaces/}
    echo "  '$w'," >> ahh-binary/src/workspace/choices.ts
done
echo "] as const;" >> ahh-binary/src/workspace/choices.ts
echo "// This file is auto-generated by setup-workspaces.sh" >> ahh-binary/src/workspace/choices.ts
echo "// Created at $(date)" >> ahh-binary/src/workspace/choices.ts

