export const WORKSPACE_CHOICES = [
  "python-pwntools-interact",
  "ts",
  "web-xss-template",
] as const;
// This file is auto-generated by setup-workspaces.sh
// Created at Sun Mar  2 20:04:23 PST 2025
