name: Build and Release Binary

on:
  push:
    branches:
      - master
    paths:
      - 'ahh-binary/**'
      - '.github/workflows/ahh-binary-build-linux.yaml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun Runtime
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
          cd ahh-binary
          bun install

      - name: Setup CLI Workspaces
        run: |
          chmod +x ./setup-workspaces.sh
          ./setup-workspaces.sh
          
      - name: Build binary
        shell: bash
        run: |
          cd ahh-binary
          bun run compile:prod

      - name: Archive dist folder
        run: |
          cd ahh-binary/dist
          tar -czvf ../ahh-dist.tar.gz *

      - name: Generate release tag
        id: tag
        run: |
          echo "release_tag=ahh_$(date +"%Y.%m.%d_%H-%M")" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: ahh-binary/ahh-dist.tar.gz
          tag_name: ${{ steps.tag.outputs.release_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
