name: Build and Release Binary

on:
  push:
    branches:
      - master 
    paths:
      - 'ahh-binary/**'  
      - '.github/workflows/ahh-binary-build-linux.yaml'  
  workflow_dispatch:
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Bun Runtime
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
          cd ahh-binary  
          bun install
        
      - name: Build binary
        run: |
          cd ahh-binary
          bun run compile:prod

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: ahh-binary/dist/ahh  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
