name: Build and Release Binary [macOS]

on:
  push:
    branches:
      - master
    paths:
      - 'ahh-binary/**'
      - '.github/workflows/ahh-binary-build-darwin.yaml'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun Runtime
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
          cd ahh-binary
          bun install

      - name: Setup CLI Workspaces
        run: |
          chmod +x ./setup-workspaces.sh
          ./setup-workspaces.sh
          
      - name: Build binary
        shell: bash
        run: |
          cd ahh-binary
          bun run compile:prod

      - name: Archive dist folder
        run: |
          cd ahh-binary/dist
          tar -czvf ../ahh-dist-darwin.tar.gz *

      - name: Generate release tag
        id: tag
        run: |
          echo "release_tag=ahh_$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Wait for Release and Upload
        run: |
          for i in {1..10}; do
            if gh release view ${{ steps.tag.outputs.release_tag }} --repo $GITHUB_REPOSITORY > /dev/null 2>&1; then
              gh release upload ${{ steps.tag.outputs.release_tag }} ahh-binary/ahh-dist-darwin.tar.gz --repo $GITHUB_REPOSITORY
              echo "Uploaded macOS binary to release"
              break
            else
              echo "Release not found yet, retrying in 10 seconds ($i/10)"
              sleep 10
            fi
          done
          if [ $i -eq 10 ]; then
            echo "Error: Release not found after 10 attempts, aborting."
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}